### ISSUE TITLE
branch: rocko meta-vuplus error

### ISSUE THREAD

**Issue by audi06** [MastaG/pli-oe-core#6]
`
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ make update
Updating Git repositories...
Already up-to-date.
Submodule 'bitbake' (git://git.openembedded.org/bitbake) registered for path 'bitbake'
Submodule 'meta-amiko' (https://github.com/open-amiko/meta-amiko.git) registered for path 'meta-amiko'
Submodule 'meta-dream' (https://github.com/DMM-PLi/meta-dream.git) registered for path 'meta-dream'
Submodule 'meta-edision' (http://github.com/edision-open/meta-edision.git) registered for path 'meta-edision'
Submodule 'meta-formuler' (https://github.com/formuler/meta-formuler.git) registered for path 'meta-formuler'
Submodule 'meta-fulan' (http://github.com/MastaG/meta-fulan.git) registered for path 'meta-fulan'
Submodule 'meta-gfutures' (https://github.com/MastaG/meta-gfutures.git) registered for path 'meta-gfutures'
Submodule 'meta-gi' (http://github.com/GIDeveloperTeam/meta-gi.git) registered for path 'meta-gi'
Submodule 'meta-gigablue' (https://github.com/GigaBlue-STB/meta-gigablue) registered for path 'meta-gigablue'
Submodule 'meta-ini' (https://github.com/MastaG/meta-ini.git) registered for path 'meta-ini'
Submodule 'meta-miraclebox' (http://github.com/miraclebox-git/meta-miraclebox.git) registered for path 'meta-miraclebox'
Submodule 'meta-openembedded' (git://git.openembedded.org/meta-openembedded) registered for path 'meta-openembedded'
Submodule 'meta-openpli/recipes-openpli/e2openplugins' (git://github.com/E2OpenPlugins/e2openplugins.git) registered for path 'meta-openpli/recipes-openpli/e2openplugins'
Submodule 'meta-qt5' (http://github.com/meta-qt5/meta-qt5.git) registered for path 'meta-qt5'
Submodule 'meta-raspberrypi' (https://github.com/RaspberryPLi/meta-raspberrypi.git) registered for path 'meta-raspberrypi'
Submodule 'meta-sab' (http://github.com/mariner2/meta-sab.git) registered for path 'meta-sab'
Submodule 'meta-spycat' (https://github.com/open-spycat/meta-spycat.git) registered for path 'meta-spycat'
Submodule 'meta-vuplus' (https://github.com/MastaG/meta-vuplus) registered for path 'meta-vuplus'
Submodule 'meta-xp' (https://github.com/XP-Master/meta-xp.git) registered for path 'meta-xp'
Submodule 'meta-xpeedc' (http://github.com/XpeedDeveloperTeam/meta-xpeedc.git) registered for path 'meta-xpeedc'
Submodule 'meta-xsarius.pli5' (http://github.com/pli3/meta-xsarius.pli5.git) registered for path 'meta-xsarius.pli5'
Submodule 'meta-xtrend' (http://github.com/XTrendTeam/meta-xtrend.git) registered for path 'meta-xtrend'
Submodule 'meta-zgemma' (https://github.com/MastaG/meta-zgemma.git) registered for path 'meta-zgemma'
Submodule 'openembedded-core' (git://git.openembedded.org/openembedded-core) registered for path 'openembedded-core'
Cloning into 'bitbake'...
remote: Counting objects: 49294, done.
remote: Compressing objects: 100% (12707/12707), done.
remote: Total 49294 (delta 37093), reused 46836 (delta 35146)
Receiving objects: 100% (49294/49294), 10.43 MiB | 731.00 KiB/s, done.
Resolving deltas: 100% (37093/37093), done.
Checking connectivity... done.
Submodule path 'bitbake': checked out 'be393f247a08c0a4a50a6a76b8fd57f78295d2a1'
Cloning into 'meta-amiko'...
remote: Counting objects: 42, done.
remote: Total 42 (delta 0), reused 0 (delta 0), pack-reused 42
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Submodule path 'meta-amiko': checked out 'b7f3170fc8e9b668ec1ccc06199278a873e0fb27'
Cloning into 'meta-dream'...
remote: Counting objects: 3202, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 3202 (delta 8), reused 14 (delta 4), pack-reused 3176
Receiving objects: 100% (3202/3202), 14.20 MiB | 753.00 KiB/s, done.
Resolving deltas: 100% (1776/1776), done.
Checking connectivity... done.
Submodule path 'meta-dream': checked out 'c50b27371316ac02e9f3075bb0d01f1e80bb20c5'
Cloning into 'meta-edision'...
remote: Counting objects: 849, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 849 (delta 0), reused 0 (delta 0), pack-reused 844
Receiving objects: 100% (849/849), 18.49 MiB | 862.00 KiB/s, done.
Resolving deltas: 100% (320/320), done.
Checking connectivity... done.
Submodule path 'meta-edision': checked out 'e4a86330d2b765679927874112b33feabaedc6ff'
Cloning into 'meta-formuler'...
remote: Counting objects: 531, done.
remote: Total 531 (delta 0), reused 0 (delta 0), pack-reused 531
Receiving objects: 100% (531/531), 199.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (183/183), done.
Checking connectivity... done.
Submodule path 'meta-formuler': checked out '8a604a73fbae8ca21d77b2a9a7e91b08e5893b30'
Cloning into 'meta-fulan'...
remote: Counting objects: 859, done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 859 (delta 43), reused 110 (delta 33), pack-reused 712
Receiving objects: 100% (859/859), 8.36 MiB | 876.00 KiB/s, done.
Resolving deltas: 100% (199/199), done.
Checking connectivity... done.
Submodule path 'meta-fulan': checked out 'c5c1b15ad24df1785ed76659863d61f9f45c2c0d'
Cloning into 'meta-gfutures'...
remote: Counting objects: 361, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 361 (delta 4), reused 11 (delta 4), pack-reused 345
Receiving objects: 100% (361/361), 207.01 KiB | 240.00 KiB/s, done.
Resolving deltas: 100% (141/141), done.
Checking connectivity... done.
Submodule path 'meta-gfutures': checked out '183e38074b5eca0efc22fc6f9c43c86b6357ef23'
Cloning into 'meta-gi'...
remote: Counting objects: 1494, done.
remote: Total 1494 (delta 0), reused 0 (delta 0), pack-reused 1494
Receiving objects: 100% (1494/1494), 661.94 KiB | 351.00 KiB/s, done.
Resolving deltas: 100% (694/694), done.
Checking connectivity... done.
Submodule path 'meta-gi': checked out '01fd1e8256f53d40371e65514e13a53ef53e400d'
Cloning into 'meta-gigablue'...
remote: Counting objects: 110, done.
remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (110/110), 582.53 KiB | 316.00 KiB/s, done.
Resolving deltas: 100% (34/34), done.
Checking connectivity... done.
Submodule path 'meta-gigablue': checked out 'ad1d13bcd2c8517309ea3188fa68e81eee728711'
Cloning into 'meta-ini'...
remote: Counting objects: 114, done.
remote: Total 114 (delta 0), reused 0 (delta 0), pack-reused 114
Receiving objects: 100% (114/114), 10.66 MiB | 713.00 KiB/s, done.
Resolving deltas: 100% (44/44), done.
Checking connectivity... done.
Submodule path 'meta-ini': checked out 'ad25d3bfaeb5d3af734442e3b7fd242cc1418aef'
Cloning into 'meta-miraclebox'...
remote: Counting objects: 322, done.
remote: Total 322 (delta 0), reused 0 (delta 0), pack-reused 322
Receiving objects: 100% (322/322), 11.96 MiB | 852.00 KiB/s, done.
Resolving deltas: 100% (137/137), done.
Checking connectivity... done.
Submodule path 'meta-miraclebox': checked out 'd44871d4d1f357d5b38488ed505b48fa8c8feff3'
Cloning into 'meta-openembedded'...
remote: Counting objects: 84706, done.
remote: Compressing objects: 100% (28752/28752), done.
remote: Total 84706 (delta 52061), reused 84211 (delta 51692)
Receiving objects: 100% (84706/84706), 27.70 MiB | 782.00 KiB/s, done.
Resolving deltas: 100% (52061/52061), done.
Checking connectivity... done.
Submodule path 'meta-openembedded': checked out '6e3fc5b8d904d06e3aa77e9ec9968ab37a798188'
Cloning into 'meta-openpli/recipes-openpli/e2openplugins'...
remote: Counting objects: 569, done.
remote: Total 569 (delta 0), reused 0 (delta 0), pack-reused 569
Receiving objects: 100% (569/569), 84.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (346/346), done.
Checking connectivity... done.
Submodule path 'meta-openpli/recipes-openpli/e2openplugins': checked out '6d14781957e2f41f8ded7d190bc25731cd8a846b'
Cloning into 'meta-qt5'...
remote: Counting objects: 7957, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7957 (delta 0), reused 1 (delta 0), pack-reused 7955
Receiving objects: 100% (7957/7957), 2.32 MiB | 543.00 KiB/s, done.
Resolving deltas: 100% (4916/4916), done.
Checking connectivity... done.
Submodule path 'meta-qt5': checked out 'd87335a50a9dd35d890786edbd79b8953fdaa11a'
Cloning into 'meta-raspberrypi'...
remote: Counting objects: 4480, done.
remote: Compressing objects: 100% (1966/1966), done.
remote: Total 4480 (delta 2328), reused 4316 (delta 2222), pack-reused 0
Receiving objects: 100% (4480/4480), 1.08 MiB | 616.00 KiB/s, done.
Resolving deltas: 100% (2328/2328), done.
Checking connectivity... done.
Submodule path 'meta-raspberrypi': checked out 'a72c24a6debbb331171c932c9f2ec9de658c3137'
Cloning into 'meta-sab'...
remote: Counting objects: 40, done.
remote: Total 40 (delta 0), reused 0 (delta 0), pack-reused 40
Unpacking objects: 100% (40/40), done.
Checking connectivity... done.
Submodule path 'meta-sab': checked out '92262feb14e4005c8096150daac7313e9cb3d85a'
Cloning into 'meta-spycat'...
remote: Counting objects: 330, done.
remote: Total 330 (delta 0), reused 0 (delta 0), pack-reused 330
Receiving objects: 100% (330/330), 84.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (120/120), done.
Checking connectivity... done.
Submodule path 'meta-spycat': checked out 'a19f11bbcdcad969e9f6f8d2c30df0653427d4cb'
Cloning into 'meta-vuplus'...
remote: Counting objects: 1591, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 1591 (delta 35), reused 78 (delta 23), pack-reused 1492
Receiving objects: 100% (1591/1591), 7.35 MiB | 736.00 KiB/s, done.
Resolving deltas: 100% (655/655), done.
Checking connectivity... done.
fatal: reference is not a tree: 409cc78e21ff0efd194d3fd2b0eb986cae2a5349
Cloning into 'meta-xp'...
remote: Counting objects: 145, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 145 (delta 4), reused 11 (delta 2), pack-reused 125
Receiving objects: 100% (145/145), 10.04 MiB | 653.00 KiB/s, done.
Resolving deltas: 100% (32/32), done.
Checking connectivity... done.
Submodule path 'meta-xp': checked out '63622f58b18506ba085d06669d49590d5ecd76f0'
Cloning into 'meta-xpeedc'...
remote: Counting objects: 397, done.
remote: Total 397 (delta 0), reused 0 (delta 0), pack-reused 397
Receiving objects: 100% (397/397), 66.92 KiB | 0 bytes/s, done.
Resolving deltas: 100% (163/163), done.
Checking connectivity... done.
Submodule path 'meta-xpeedc': checked out 'f12908a5573de8a6a06ad9f75081846a590511c4'
Cloning into 'meta-xsarius.pli5'...
remote: Counting objects: 256, done.
remote: Total 256 (delta 0), reused 0 (delta 0), pack-reused 256
Receiving objects: 100% (256/256), 2.80 MiB | 763.00 KiB/s, done.
Resolving deltas: 100% (122/122), done.
Checking connectivity... done.
Submodule path 'meta-xsarius.pli5': checked out 'af31685f1d8c1d982e01d660bfb6795026d841a4'
Cloning into 'meta-xtrend'...
remote: Counting objects: 1015, done.
remote: Total 1015 (delta 0), reused 0 (delta 0), pack-reused 1015
Receiving objects: 100% (1015/1015), 601.49 KiB | 373.00 KiB/s, done.
Resolving deltas: 100% (513/513), done.
Checking connectivity... done.
Submodule path 'meta-xtrend': checked out '1502e5d07a3e61001a89bbceeecd3e4a44d2bed8'
Cloning into 'meta-zgemma'...
remote: Counting objects: 458, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 458 (delta 1), reused 6 (delta 1), pack-reused 448
Receiving objects: 100% (458/458), 204.56 KiB | 311.00 KiB/s, done.
Resolving deltas: 100% (158/158), done.
Checking connectivity... done.
Submodule path 'meta-zgemma': checked out '66c11294fe069e981eb938fd885052b3d2970e05'
Cloning into 'openembedded-core'...
remote: Counting objects: 302097, done.
remote: Compressing objects: 100% (78817/78817), done.
remote: Total 302097 (delta 218296), reused 301774 (delta 218017)
Receiving objects: 100% (302097/302097), 100.88 MiB | 892.00 KiB/s, done.
Resolving deltas: 100% (218296/218296), done.
Checking connectivity... done.
Submodule path 'openembedded-core': checked out '3b413a80578caacd9a7f405f3c51a3921d78a60d'
Unable to checkout '409cc78e21ff0efd194d3fd2b0eb986cae2a5349' in submodule path 'meta-vuplus'
Makefile:137: recipe for target 'update' failed
make: *** [update] Error 1
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ make update
Updating Git repositories...
Already up-to-date.
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-amiko'
Synchronizing submodule url for 'meta-dream'
Synchronizing submodule url for 'meta-edision'
Synchronizing submodule url for 'meta-formuler'
Synchronizing submodule url for 'meta-fulan'
Synchronizing submodule url for 'meta-gfutures'
Synchronizing submodule url for 'meta-gi'
Synchronizing submodule url for 'meta-gigablue'
Synchronizing submodule url for 'meta-ini'
Synchronizing submodule url for 'meta-miraclebox'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-openpli/recipes-openpli/e2openplugins'
Synchronizing submodule url for 'meta-qt5'
Synchronizing submodule url for 'meta-raspberrypi'
Synchronizing submodule url for 'meta-sab'
Synchronizing submodule url for 'meta-spycat'
Synchronizing submodule url for 'meta-vuplus'
Synchronizing submodule url for 'meta-xp'
Synchronizing submodule url for 'meta-xpeedc'
Synchronizing submodule url for 'meta-xsarius.pli5'
Synchronizing submodule url for 'meta-xtrend'
Synchronizing submodule url for 'meta-zgemma'
Synchronizing submodule url for 'openembedded-core'
fatal: reference is not a tree: 409cc78e21ff0efd194d3fd2b0eb986cae2a5349
Unable to checkout '409cc78e21ff0efd194d3fd2b0eb986cae2a5349' in submodule path 'meta-vuplus'
Makefile:137: recipe for target 'update' failed
make: *** [update] Error 1
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ git status
On branch rocko
Your branch is up-to-date with 'origin/rocko'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   meta-vuplus (new commits, modified content)

no changes added to commit (use "git add" and/or "git commit -a")
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ git reset --hard
HEAD is now at 46fff59 Merge pull request #5 from fairbird/rocko
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ git pull
Already up-to-date.
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ make update
Updating Git repositories...
Already up-to-date.
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-amiko'
Synchronizing submodule url for 'meta-dream'
Synchronizing submodule url for 'meta-edision'
Synchronizing submodule url for 'meta-formuler'
Synchronizing submodule url for 'meta-fulan'
Synchronizing submodule url for 'meta-gfutures'
Synchronizing submodule url for 'meta-gi'
Synchronizing submodule url for 'meta-gigablue'
Synchronizing submodule url for 'meta-ini'
Synchronizing submodule url for 'meta-miraclebox'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-openpli/recipes-openpli/e2openplugins'
Synchronizing submodule url for 'meta-qt5'
Synchronizing submodule url for 'meta-raspberrypi'
Synchronizing submodule url for 'meta-sab'
Synchronizing submodule url for 'meta-spycat'
Synchronizing submodule url for 'meta-vuplus'
Synchronizing submodule url for 'meta-xp'
Synchronizing submodule url for 'meta-xpeedc'
Synchronizing submodule url for 'meta-xsarius.pli5'
Synchronizing submodule url for 'meta-xtrend'
Synchronizing submodule url for 'meta-zgemma'
Synchronizing submodule url for 'openembedded-core'
fatal: reference is not a tree: 409cc78e21ff0efd194d3fd2b0eb986cae2a5349
Unable to checkout '409cc78e21ff0efd194d3fd2b0eb986cae2a5349' in submodule path 'meta-vuplus'
Makefile:137: recipe for target 'update' failed
make: *** [update] Error 1
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ 

`

**Comment by audi06** [comment]
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ cd meta-dream && git pull origin rocko && cd ..
From https://github.com/DMM-PLi/meta-dream
 * branch            rocko      -> FETCH_HEAD
Updating c50b273..7b95738
Fast-forward
 README.md                                                                                                  | 14 +++++++-------
 recipes-bsp/linux/linux-dreambox-3.2/clear_sublevel.patch                                                  |  4 ++--
 recipes-bsp/linux/linux-dreambox_3.2.bb                                                                    |  8 ++++----
 recipes-openpli/enigma2/enigma2.bbappend                                                                   | 18 ++++++++++++++----
 .../enigma2/enigma2/{dual-tuner-letter-detection-dm7080.patch => dual-tuner-letter-detection.patch}        |  4 ++--
 recipes-openpli/enigma2/enigma2/tryfix-snr-si216x-tuners.patch                                             | 18 +++++-------------
 recipes-openpli/enigma2/enigma2/tryfix-videomode.patch                                                     | 16 ----------------
 7 files changed, 34 insertions(+), 48 deletions(-)
 rename recipes-openpli/enigma2/enigma2/{dual-tuner-letter-detection-dm7080.patch => dual-tuner-letter-detection.patch} (93%)
 delete mode 100644 recipes-openpli/enigma2/enigma2/tryfix-videomode.patch
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$ ## MACHINE=dm900 make image
Generating /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/build/env.source
Generating /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/build/conf/openpli.conf
Generating /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/build/conf/bblayers.conf
Generating /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/build/conf/local.conf
Building image for dm900
ERROR: Unable to start bitbake server
ERROR: Last 10 lines of server log for this session (/home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/build/bitbake-cookerdaemon.log):
    return bb.parse.handle(fn, data, include)
  File "/home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/bitbake/lib/bb/parse/__init__.py", line 117, in handle
    return h['handle'](fn, data, include)
  File "/home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 134, in handle
    abs_fn = resolve_file(fn, data)
  File "/home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/bitbake/lib/bb/parse/__init__.py", line 140, in resolve_file
    raise IOError(errno.ENOENT, "file %s not found" % fn)
FileNotFoundError: [Errno 2] file /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/meta-vuplus/conf/layer.conf not found

ERROR: Unable to parse /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/meta-vuplus/conf/layer.conf: [Errno 2] file /home/dreamosat/Genel/OpenPLi-DM/pli-oe-core/meta-vuplus/conf/layer.conf not found

Makefile:129: recipe for target 'image' failed
make: *** [image] Error 1
dreamosat@debian:~/Genel/OpenPLi-DM/pli-oe-core$

**Comment by Hains** [comment]
Solved.
Run
```
make update
```
Or clone again.

**Comment by Hains** [comment]
You can safely remove the two bbappends:
meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.2.0.bbappend
meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-omx_git.bbappend

You don't need them.

**Comment by persianpros** [comment]
If you have time please update meta-raspberrypi in all 3 branches.
Thanks in advance.

**Comment by Hains** [comment]
Done
